# Generated by Django 2.1.1 on 2018-09-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='allergens',
            field=models.CharField(default='None', max_length=64, verbose_name='Аллергены'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='rating',
            field=models.IntegerField(default=0, null=True, verbose_name='Рейтинг'),
        ),
    ]
