# Generated by Django 2.1.1 on 2018-09-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180915_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='img',
            field=models.ImageField(default='files/static/menu/img/raw_meat.svg', upload_to='files/static/menu/img/menu_img'),
        ),
    ]
