# Generated by Django 2.1.1 on 2018-09-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='img',
            field=models.ImageField(default='menu/img/raw_meat.svg', upload_to='uploads/'),
        ),
    ]
